cacheFolder: .next/cache/yarn

compressionLevel: mixed

enableGlobalCache: false

installStatePath: .next/cache/yarn-install-state.gz

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.3.cjs
